name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: 1.5
    - run: julia --project=@. -e '
            import Pkg; Pkg.activate("page/Project.toml"); Pkg.instantiate();
            using InteractiveUtils; versioninfo(); Pkg.build(); using FinancialToolbox;
            Pkg.add(["NodeJS", "PkgPage"]);
            using NodeJS;
            run(`$(npm_cmd()) install highlight.js purgecss`);
            import PkgPage;
            PkgPage.optimize(input="page", output="")'
    - run: touch page/__site/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages
        FOLDER: page/__site
