name: PkgJogger
on:
    - push
    - pull_request

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@latest
            - name: Run Benchmarks
              run: julia --project=benchmark -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); using PkgJogger; PkgJogger.ci();'
            - uses: actions/upload-artifact@v2
              with:
                name: benchmarks
                path: benchmark/trial/*
